{{- if .Values.datagrid.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhbk-datagrid.datagrid" . }}
  labels:
    {{- include "rhbk-datagrid.datagridLabels" . | nindent 4 }}
type: Opaque
stringData:
  DATAGRID_USERNAME: {{ .Values.datagrid.credentials.username | quote }}
  DATAGRID_PASSWORD: {{ .Values.datagrid.credentials.password | quote }}
{{- end }}
