{{- if .Values.datagrid.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rhbk-datagrid.datagrid" . }}-config
  labels:
    {{- include "rhbk-datagrid.datagridLabels" . | nindent 4 }}
data:
  infinispan.xml: |
    <infinispan
        xmlns="urn:infinispan:config:15.0"
        xmlns:server="urn:infinispan:server:15.0">

      <cache-container name="default" statistics="true">
        <transport cluster="${infinispan.cluster.name:{{ .Values.datagrid.clusterName }}}"
                   stack="${infinispan.cluster.stack:kubernetes}"
                   node-name="${infinispan.node.name:}"/>
        <security>
          <authorization/>
        </security>

        <distributed-cache name="sessions" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="actionTokens" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
        <distributed-cache name="work" mode="SYNC" owners="2">
          <encoding media-type="application/x-protostream"/>
        </distributed-cache>
      </cache-container>

      <server xmlns="urn:infinispan:server:15.0">
        <interfaces>
          <interface name="public">
            <inet-address value="${infinispan.bind.address:0.0.0.0}"/>
          </interface>
        </interfaces>

        <socket-bindings default-interface="public"
                         port-offset="${infinispan.socket.binding.port-offset:0}">
          <socket-binding name="default" port="11222"/>
        </socket-bindings>

        <security>
          <credential-stores>
            <credential-store name="credentials" path="credentials.pfx">
              <clear-text-credential clear-text="secret"/>
            </credential-store>
          </credential-stores>
          <security-realms>
            <security-realm name="default">
              <properties-realm groups-attribute="Roles">
                <user-properties path="users.properties"/>
                <group-properties path="groups.properties"/>
              </properties-realm>
            </security-realm>
          </security-realms>
        </security>

        <endpoints socket-binding="default" security-realm="default"/>
      </server>
    </infinispan>
{{- end }}
