apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhbk-datagrid.rhbk" . }}
  labels:
    {{- include "rhbk-datagrid.rhbkLabels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
  {{- if .Values.postgresql.enabled }}
  KC_DB_USERNAME: {{ .Values.postgresql.credentials.username | quote }}
  KC_DB_PASSWORD: {{ .Values.postgresql.credentials.password | quote }}
  {{- end }}
  {{- if .Values.datagrid.enabled }}
  KC_CACHE_REMOTE_USERNAME: {{ .Values.datagrid.credentials.username | quote }}
  KC_CACHE_REMOTE_PASSWORD: {{ .Values.datagrid.credentials.password | quote }}
  {{- end }}
